export {default as BlogCC} from './blog/BlogCC'
export {default as FeaturesCC} from './features/FeatureCC'
export {default as FooterCC} from './footer/FooterCC'
export {default as HeaderCC} from './header/HeaderCC'
export {default as PossibilityCC} from './possibility/PossibilityCC'
export {default as WhatGPT3CC} from './whatGPT3/WhatGPT3CC'